project_id = "zoripeohnedivxkvrpbi"

[functions.live-start]
verify_jwt = false

[functions.live-stop]
verify_jwt = false

[functions.devices-heartbeat]
verify_jwt = false

[functions.whatsapp-send-otp]
verify_jwt = false

[functions.whatsapp-verify-otp]
verify_jwt = false

[functions.validate-session]
verify_jwt = false
